# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4
FROM node:lts-alpine AS builder
WORKDIR /app

# Install build dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci --ignore-scripts
RUN npm run build

FROM node:lts-alpine AS runner
WORKDIR /app
# Copy production dependencies and build artifacts
COPY --from=builder /app/package.json /app/package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts
COPY --from=builder /app/dist ./dist

# Expose default port
ENV PORT=1071
EXPOSE 1071

# Start in production stateless mode
CMD ["node", "dist/stateless-production-server.js"]
